In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [6]:
dataset = pd.read_csv('insurance.csv')

In [4]:
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
label = LabelEncoder()
label.fit(dataset.sex.drop_duplicates())
dataset.sex = label.transform(dataset.sex)

#smoker or not
label.fit(dataset.smoker.drop_duplicates())
dataset.smoker = label.transform(dataset.smoker)

#region 
label.fit(dataset.region.drop_duplicates())
dataset.region = label.transform(dataset.region)

dataset

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [8]:
x_lin = dataset.drop(['charges'], axis = 1)
y_lin = dataset[['charges']]

x_lin_train, x_lin_test, y_lin_train , y_lin_test = train_test_split(x_lin, y_lin,  test_size = 0.3, random_state=42)

In [19]:
y_lin

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
Linear_model = LinearRegression()
Linear_model.fit(x_lin_train, y_lin_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
pred = Linear_model.predict(x_lin_test)

In [12]:
pred

array([[ 8.93142116e+03],
       [ 7.07090670e+03],
       [ 3.69370805e+04],
       [ 9.59699214e+03],
       [ 2.70083549e+04],
       [ 1.08664849e+04],
       [ 3.74610217e+01],
       [ 1.72228092e+04],
       [ 9.18308115e+02],
       [ 1.13965537e+04],
       [ 2.79154456e+04],
       [ 9.53381323e+03],
       [ 5.18928014e+03],
       [ 3.86124990e+04],
       [ 4.05094490e+04],
       [ 3.72748566e+04],
       [ 1.53562559e+04],
       [ 3.59449407e+04],
       [ 9.10631783e+03],
       [ 3.14429410e+04],
       [ 3.66298253e+03],
       [ 1.00966745e+04],
       [ 2.21091896e+03],
       [ 7.10598084e+03],
       [ 1.13521417e+04],
       [ 1.30231210e+04],
       [ 1.44472857e+04],
       [ 6.12031303e+03],
       [ 9.94564893e+03],
       [ 2.18617424e+03],
       [ 8.91389260e+03],
       [ 1.31869496e+04],
       [ 4.49110116e+03],
       [ 3.30469662e+03],
       [ 4.32885102e+03],
       [ 1.32330189e+04],
       [ 1.67071398e+03],
       [ 8.63238607e+03],
       [ 3.32727214e+04],
       [ 3.26840062e+04],
       [ 3.60294190e+03],
       [ 4.40040903e+03],
       [ 1.40663345e+04],
       [ 1.16268203e+04],
       [ 8.89219642e+03],
       [ 1.21011367e+04],
       [ 5.23906853e+03],
       [ 2.84241293e+03],
       [ 3.56294259e+04],
       [ 9.27854339e+03],
       [ 1.59720792e+04],
       [ 2.34524488e+03],
       [ 1.24695907e+04],
       [ 1.45575199e+03],
       [ 1.36060478e+04],
       [ 1.27386152e+04],
       [ 4.36613796e+03],
       [ 3.22719994e+04],
       [ 1.32349447e+04],
       [ 1.29578859e+04],
       [ 1.40951649e+04],
       [ 1.05369676e+04],
       [ 1.64362140e+04],
       [ 7.75461795e+03],
       [ 1.18779662e+04],
       [ 3.99480572e+03],
       [ 2.64330928e+04],
       [ 1.10659605e+04],
       [ 2.03158533e+03],
       [ 6.13115399e+03],
       [ 1.08767882e+04],
       [ 1.16479288e+04],
       [ 1.10243957e+04],
       [ 9.28705268e+03],
       [ 1.21416074e+04],
       [ 6.70998959e+03],
       [ 7.30925330e+03],
       [ 1.07977596e+04],
       [ 6.52692249e+03],
       [ 8.55728949e+03],
       [ 3.80852363e+03],
       [ 3.67844754e+04],
       [ 6.14441916e+03],
       [ 3.07570013e+04],
       [ 3.50094357e+04],
       [ 3.54124821e+04],
       [ 7.09149212e+03],
       [ 1.31006630e+04],
       [ 9.98014918e+03],
       [ 1.45154809e+04],
       [ 1.78305771e+04],
       [ 3.52686158e+04],
       [ 3.29784225e+04],
       [ 6.22933443e+03],
       [ 3.20886288e+04],
       [ 9.43560516e+03],
       [ 2.94772073e+04],
       [ 3.58517664e+03],
       [ 2.82020377e+04],
       [ 5.72599261e+03],
       [ 5.36908283e+03],
       [ 1.58445451e+03],
       [ 1.16903588e+04],
       [ 1.51280855e+04],
       [ 1.18546309e+04],
       [ 4.35394125e+03],
       [ 1.00266822e+04],
       [ 3.17802817e+04],
       [-1.48104195e+02],
       [ 3.27772034e+04],
       [ 3.14119000e+03],
       [ 1.03506397e+04],
       [ 1.43957986e+04],
       [ 3.15739258e+04],
       [ 1.14847275e+04],
       [ 3.79273137e+03],
       [ 1.32950567e+04],
       [ 3.15750153e+04],
       [ 8.12355507e+03],
       [ 3.28730085e+03],
       [ 8.41136792e+03],
       [ 1.07776201e+04],
       [ 1.53125155e+04],
       [ 5.72672481e+03],
       [ 3.69907719e+03],
       [ 1.02751918e+04],
       [ 1.09365360e+04],
       [ 1.12670571e+04],
       [ 1.45465772e+04],
       [ 7.54959534e+03],
       [ 5.32238745e+03],
       [ 9.34711885e+03],
       [ 9.34370053e+03],
       [ 1.25996636e+04],
       [ 8.16069315e+03],
       [ 1.54087671e+04],
       [ 8.52238619e+03],
       [ 3.17112944e+04],
       [ 3.58615001e+04],
       [ 3.15416516e+04],
       [ 5.99075866e+03],
       [ 1.26637568e+04],
       [ 6.09837646e+03],
       [ 1.46914670e+04],
       [ 2.50155681e+03],
       [ 3.28754173e+04],
       [ 6.36065967e+03],
       [ 4.79287176e+03],
       [ 1.44614304e+04],
       [ 6.85575464e+03],
       [ 3.87691431e+04],
       [ 3.01513756e+03],
       [ 5.97616737e+03],
       [ 3.17494933e+04],
       [ 1.16517535e+04],
       [ 8.58762133e+03],
       [ 1.50293832e+04],
       [ 9.82274269e+03],
       [ 2.69822534e+04],
       [ 3.35479130e+04],
       [ 1.46237783e+04],
       [ 1.57471099e+03],
       [ 1.31790001e+04],
       [ 2.20744054e+03],
       [ 5.32298532e+03],
       [ 1.17395267e+04],
       [ 3.97487819e+04],
       [ 3.65786298e+04],
       [ 3.41034394e+04],
       [ 3.63657142e+03],
       [ 7.23905466e+03],
       [ 8.48169987e+03],
       [ 1.26452175e+04],
       [ 4.88932998e+03],
       [ 1.74915089e+03],
       [ 3.21887949e+04],
       [ 2.49014504e+04],
       [ 1.77835495e+04],
       [ 2.62715499e+04],
       [ 1.02083595e+04],
       [ 3.72965033e+04],
       [-6.52360342e+02],
       [ 6.88231317e+03],
       [ 7.58702522e+03],
       [ 4.36293824e+03],
       [ 5.07700999e+03],
       [ 5.96907983e+03],
       [ 4.04888331e+03],
       [ 1.53182327e+04],
       [ 1.13331480e+04],
       [ 6.83898258e+03],
       [ 2.39352108e+03],
       [ 1.37792303e+03],
       [ 3.18527846e+04],
       [ 1.66917992e+04],
       [ 1.20745723e+04],
       [ 1.14919812e+03],
       [ 1.25625910e+04],
       [ 1.41156831e+03],
       [ 8.55785296e+03],
       [ 1.77064557e+03],
       [ 3.40708782e+04],
       [ 1.10256141e+04],
       [ 2.63243650e+03],
       [ 2.55079532e+04],
       [ 2.61948641e+04],
       [ 9.59950672e+03],
       [ 1.66993572e+03],
       [ 1.34838387e+04],
       [ 7.87765692e+02],
       [ 1.03599201e+04],
       [ 1.05819030e+04],
       [ 1.70814008e+04],
       [ 2.68387842e+04],
       [ 7.00938297e+03],
       [ 5.10751649e+03],
       [ 5.78098372e+03],
       [ 1.32803923e+04],
       [ 1.11319095e+04],
       [ 8.35083139e+03],
       [ 5.11042689e+03],
       [ 1.25467353e+04],
       [ 1.40772626e+04],
       [ 3.59251544e+04],
       [ 4.23789294e+03],
       [ 2.89538327e+04],
       [-1.27526758e+03],
       [ 2.92930773e+03],
       [ 1.12062922e+04],
       [ 1.57880970e+04],
       [ 5.28294712e+03],
       [ 6.87109043e+03],
       [ 3.56790897e+03],
       [ 3.12149215e+04],
       [ 7.23091139e+03],
       [ 1.26084664e+04],
       [ 5.70762316e+03],
       [ 9.50312570e+03],
       [ 3.63497801e+04],
       [ 4.48337473e+03],
       [ 9.65037954e+03],
       [ 3.10538973e+04],
       [ 5.73141678e+03],
       [ 4.51810286e+03],
       [ 1.06359747e+03],
       [ 4.92434635e+03],
       [ 4.30546329e+03],
       [ 6.41542240e+03],
       [ 1.88165410e+04],
       [-1.58767500e+03],
       [ 2.08726159e+03],
       [ 1.06664386e+04],
       [ 2.87099675e+03],
       [ 1.02075046e+04],
       [ 3.66954356e+03],
       [ 5.05237573e+03],
       [ 1.24207550e+04],
       [ 6.33066928e+03],
       [ 8.32234154e+03],
       [ 7.52601017e+03],
       [ 8.93227534e+03],
       [ 1.05347636e+04],
       [ 2.78205086e+04],
       [ 3.92856297e+04],
       [ 1.18447191e+04],
       [ 7.76727113e+03],
       [ 4.10661436e+04],
       [ 1.22069344e+04],
       [ 7.06633749e+03],
       [ 8.31134638e+03],
       [ 9.15260379e+03],
       [ 1.11327147e+04],
       [ 1.01074213e+04],
       [ 1.78630232e+04],
       [ 7.84425363e+02],
       [ 2.35054301e+04],
       [ 1.28402370e+04],
       [ 3.32540123e+04],
       [ 5.21396476e+03],
       [ 1.33702622e+04],
       [ 1.04393089e+04],
       [ 1.79306010e+04],
       [ 9.81175719e+03],
       [ 1.15961440e+04],
       [ 3.21617330e+04],
       [ 3.31986358e+03],
       [ 1.37496402e+04],
       [ 3.95683833e+04],
       [ 5.54333858e+03],
       [ 6.23384509e+03],
       [ 3.34274209e+03],
       [ 1.13602421e+04],
       [ 2.53553476e+04],
       [ 1.42751792e+04],
       [ 9.36322233e+03],
       [ 1.01541781e+04],
       [ 1.36846064e+04],
       [ 7.04846551e+02],
       [ 2.40293110e+03],
       [ 3.08256247e+04],
       [ 2.98939248e+04],
       [ 1.37971445e+04],
       [ 3.66840086e+03],
       [ 2.54033560e+04],
       [ 1.36099681e+04],
       [ 3.08035817e+04],
       [ 3.40774884e+03],
       [ 3.91303562e+04],
       [ 1.13520181e+04],
       [ 4.88112196e+03],
       [ 6.63012225e+03],
       [ 2.57264447e+03],
       [ 2.58941048e+04],
       [ 1.43159019e+04],
       [ 3.67727374e+02],
       [ 1.26690993e+04],
       [ 1.28517230e+04],
       [ 1.50524315e+04],
       [ 3.51550959e+04],
       [ 1.44614312e+04],
       [ 3.16849510e+04],
       [ 9.88814606e+03],
       [ 1.82342812e+04],
       [ 5.85771654e+03],
       [ 8.99261803e+03],
       [ 9.27620101e+03],
       [ 1.54708619e+04],
       [ 8.98736496e+03],
       [ 8.41456605e+03],
       [ 1.50608819e+04],
       [ 1.28253602e+04],
       [ 1.49321014e+04],
       [ 7.38658206e+03],
       [ 2.61065024e+04],
       [ 9.37846298e+03],
       [ 1.84801777e+03],
       [ 4.29082654e+03],
       [ 1.42115781e+04],
       [ 3.58650882e+04],
       [ 9.49708847e+03],
       [ 1.28255300e+04],
       [ 5.29979460e+03],
       [ 4.97447308e+03],
       [ 3.81342220e+03],
       [ 2.72083867e+03],
       [ 9.03161410e+03],
       [ 7.19875937e+03],
       [ 2.49342629e+03],
       [ 1.30461468e+04],
       [ 8.90160139e+03],
       [ 5.81259221e+03],
       [ 5.38198278e+02],
       [ 9.31275778e+03],
       [ 4.97277878e+03],
       [ 3.31106597e+04],
       [ 2.85736717e+04],
       [ 3.70597724e+04],
       [ 5.48953746e+03],
       [ 8.72326591e+03],
       [ 8.39711736e+03],
       [ 3.36207746e+03],
       [ 3.16373339e+04],
       [ 7.14468257e+03],
       [ 2.84245186e+04],
       [ 3.62304876e+04],
       [ 7.13435976e+03],
       [ 1.28623795e+04],
       [ 9.91674109e+03],
       [ 8.34333364e+03],
       [ 1.27928552e+04],
       [ 3.01641764e+04],
       [ 1.71595116e+04],
       [ 1.20106593e+04],
       [ 4.00580087e+03],
       [-1.43018949e+03],
       [ 1.22043703e+04],
       [ 3.07650613e+04],
       [ 1.31623933e+04],
       [ 1.12000279e+04],
       [ 7.95694801e+03],
       [ 3.61330671e+03],
       [ 7.02240292e+03],
       [ 7.06987605e+03],
       [ 1.05760938e+04],
       [ 3.37742354e+04],
       [ 3.90910529e+04],
       [ 1.18223109e+04],
       [ 8.34561825e+03],
       [ 1.66015909e+04],
       [ 1.57702432e+04],
       [ 9.51209017e+03],
       [ 9.18903542e+03],
       [ 8.93273210e+03],
       [ 2.58258875e+03],
       [ 1.00252352e+04],
       [ 3.92756091e+03],
       [ 1.05130405e+04],
       [ 1.61335516e+04],
       [ 6.74383693e+03],
       [ 2.06620349e+03],
       [ 1.46977981e+04],
       [ 2.73823510e+00]])

In [14]:
Linear_model.score(x_lin_test, pred)

1.0

In [16]:
for idx, col_name in enumerate(x_lin_train.columns):
    print("The coefficint for {} is {}".format(col_name, Linear_model.coef_[0][idx]))

The coefficint for age is 261.62568984274697
The coefficint for sex is 109.64719595059363
The coefficint for bmi is 344.54483065603455
The coefficint for children is 424.3701659576304
The coefficint for smoker is 23620.80252148175
The coefficint for region is -326.4626252721913

In [17]:
intercept = Linear_model.intercept_[0]
intercept

-12364.391322279207